# Trying to follow the method described in:
#     https://simonbinder.eu/posts/build_directory_moves/
# It's not quite working, see:
#    https://github.com/dart-lang/source_gen/issues/570
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'